import { CharacterData } from '../../types';

export const PLAYER_CHARACTERS: CharacterData[] = [
    {
        name: 'Wolverine',
        scale: 0.009,
        model: '/assets/models/v2/wolverine/scene.gltf',
        description: 'Blue Team',
        team: 'BLUE',
        imageUrl: '/assets/characters/wolverine.png',
        portraitUrl: '/assets/characters/wolverine_portrait.png',
        iconUrl: '/assets/icons/wolverine-mark.png',
        iconDeadUrl: '/assets/icons/wolverine-dead-mark.png',
        fixedHeight: 1
    },
    {
        name: 'Anthony Stark',
        scale: 1.0,
        model: '/assets/models/Cesium_Man.gltf',
        description: 'Blue Team',
        team: 'BLUE',
        imageUrl: '/assets/characters/ironman.png',
        portraitUrl: '/assets/characters/ironman_portrait.png',
        iconUrl: '/assets/icons/ironman-mark.png',
        iconDeadUrl: '/assets/icons/ironman-dead-mark.png',
    },
    {
        name: 'Peter Parker',
        scale: 1.01,
        model: '/assets/models/spiderman.gltf',
        description: 'Red Team',
        team: 'RED',
        imageUrl: '/assets/characters/spiderman.png',
        portraitUrl: '/assets/characters/spiderman_portrait.png',
        iconUrl: '/assets/icons/spiderman-mark.png',
        iconDeadUrl: '/assets/icons/spiderman-dead-mark.png',
    },
    {
        name: 'Bruce Wayne',
        scale: 0.01,
        model: '/assets/models/batman.gltf',
        description: 'Red Team',
        team: 'RED',
        imageUrl: '/assets/characters/batman.png',
        portraitUrl: '/assets/characters/batman_portrait.png',
        iconUrl: '/assets/icons/batman-mark.png',
        iconDeadUrl: '/assets/icons/batman-dead-mark.png',
    },
    {
        name: 'car',
        model: '/assets/models/untitled5.gltf',
        scale: 1,
        description: null,
        team: null,
        imageUrl: null,
        portraitUrl: null,
        iconUrl: '/assets/icons/car-mark.png',
        iconDeadUrl: '/assets/icons/car-dead-mark.png',
    },
    {
        name: 'grandpa',
        model: '/assets/models/untitled5.gltf',
        scale: 1,
        description: null,
        team: null,
        imageUrl: null,
        portraitUrl: null,
        iconUrl: '/assets/icons/grandmother-mark.png',
        iconDeadUrl: '/assets/icons/grandmother-dead-mark.png',
    },
    {
        name: 'deer',
        model: '/assets/models/deer.gltf',
        scale: 1,
        description: null,
        team: null,
        imageUrl: null,
        portraitUrl: null,
        iconUrl: '/assets/icons/deer-mark.png',
        iconDeadUrl: '/assets/icons/deer-dead-mark.png',
    },
    {
        name: 'kangaroo',
        model: '/assets/models/kangaroo.gltf',
        scale: 0.013,
        description: null,
        team: null,
        imageUrl: null,
        portraitUrl: null,
        iconUrl: '/assets/icons/grandmother-mark.png',
        iconDeadUrl: '/assets/icons/grandmother-dead-mark.png',
    },
];