import { CharacterData } from '../../types';

export const PLAYER_CHARACTERS: CharacterData[] = [
    {
        name: 'Captain America',
        scale: 1.0,
        model: '/assets/models/CaptainAmerica.gltf',
        description: 'Blue Team',
        team: 'BLUE',
        imageUrl: '/assets/characters/captain_america.png',
        portraitUrl: '/assets/characters/portrait_captain_america.png',
        iconUrl: '/assets/icons/captain_america-mark.png',
        iconDeadUrl: '/assets/icons/captain_america-mark-dead.png',
        fixedHeight: 1
    },
    {
        name: 'Anthony Stark',
        scale: 1.0,
        model: '/assets/models/ironman.gltf',
        description: 'Blue Team',
        team: 'BLUE',
        imageUrl: '/assets/characters/ironman.png',
        portraitUrl: '/assets/characters/ironman_portrait.png',
        iconUrl: '/assets/icons/ironman-mark.png',
        iconDeadUrl: '/assets/icons/ironman-dead-mark.png',
    },
    {
        name: 'Peter Parker',
        scale: 1.01,
        model: '/assets/models/spiderman.gltf',
        description: 'Red Team',
        team: 'RED',
        imageUrl: '/assets/characters/spiderman.png',
        portraitUrl: '/assets/characters/spiderman_portrait.png',
        iconUrl: '/assets/icons/spiderman-mark.png',
        iconDeadUrl: '/assets/icons/spiderman-dead-mark.png',
    },
    {
        name: 'Wade Wilson',
        scale: 1.00,
        model: '/assets/models/deadpool.gltf',
        description: 'Red Team',
        team: 'RED',
        imageUrl: '/assets/characters/deadpool.png',
        portraitUrl: '/assets/characters/deadpool_portrait.png',
        iconUrl: '/assets/icons/deadpool-mark.png',
        iconDeadUrl: '/assets/icons/deadpool-mark-dead.png',
    },
    {
        name: 'Natasha Romanova',
        scale: 1.00,
        model: '/assets/models/black_widow.gltf',
        description: 'Red Team',
        team: 'RED',
        imageUrl: '/assets/characters/blackwidow.png',
        portraitUrl: '/assets/characters/blackwidow_portrait.png',
        iconUrl: '/assets/icons/blackwidow-mark.png',
        iconDeadUrl: '/assets/icons/blackwidow-mark-dead.png',
    },
    {
        name: 'Bruce Wayne',
        scale: 0.01,
        model: '/assets/models/batman.gltf',
        description: 'Red Team',
        team: 'RED',
        imageUrl: '/assets/characters/batman.png',
        portraitUrl: '/assets/characters/batman_portrait.png',
        iconUrl: '/assets/icons/batman-mark.png',
        iconDeadUrl: '/assets/icons/batman-dead-mark.png',
    },
    {
        name: 'car',
        model: '/assets/models/car.gltf',
        scale: 1,
        description: null,
        team: null,
        imageUrl: null,
        portraitUrl: null,
        iconUrl: '/assets/icons/car-mark.png',
        iconDeadUrl: '/assets/icons/car-dead-mark.png',
    },
    {
        name: 'newCar',
        model: '/assets/models/car.gltf',
        scale: 1,
        description: null,
        team: null,
        imageUrl: null,
        portraitUrl: null,
        iconUrl: '/assets/icons/car-mark.png',
        iconDeadUrl: '/assets/icons/car-dead-mark.png',
    },
    {
        name: 'grandpa',
        model: '/assets/models/grandpa.gltf',
        scale: 0.035,
        description: null,
        team: null,
        imageUrl: null,
        portraitUrl: null,
        iconUrl: '/assets/icons/grandpa-mark.png',
        iconDeadUrl: '/assets/icons/grandpa-dead-mark.png',
    },
    {
        name: 'deer',
        model: '/assets/models/deer.gltf',
        scale: 1,
        description: null,
        team: null,
        imageUrl: null,
        portraitUrl: null,
        iconUrl: '/assets/icons/deer-mark.png',
        iconDeadUrl: '/assets/icons/deer-dead-mark.png',
    },
    {
        name: 'rhino',
        model: '/assets/models/rhino.gltf',
        scale: 2,
        description: null,
        team: null,
        imageUrl: null,
        portraitUrl: null,
        iconUrl: '/assets/icons/rhino-mark.png',
        iconDeadUrl: '/assets/icons/rhino-dead-mark.png',
    },
    {
        name: 'indianWoman',
        model: '/assets/models/indianWoman.gltf',
        scale: 0.5,
        description: null,
        team: null,
        imageUrl: null,
        portraitUrl: null,
        iconUrl: '/assets/icons/indianwoman-mark.png',
        iconDeadUrl: '/assets/icons/indianwoman-dead-mark.png',
    },
    {
        name: 'kangaroo',
        model: '/assets/models/kangaroo.gltf',
        scale: 0.013,
        description: null,
        team: null,
        imageUrl: null,
        portraitUrl: null,
        iconUrl: '/assets/icons/kangaroo-mark.png',
        iconDeadUrl: '/assets/icons/kangaroo-dead-mark.png',
    },
];
